name: 'Black_Jack_is_still_at_large'
version: 0.0.1
description: Western Roguelike based on a unique Blackjack inspired game mechanic for action resolution.
#author: Luca Carbone <tndwolf@gmail.com>
#homepage: https://twitter.com/tndwolf

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  my_dependency: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
